Rename the Match class to OrderMatch
"match" is a reserved word in PHP 8, and causes the following error
when trying to run tests that make use of "expects" in mocks:

ParseError: syntax error, unexpected token "match", expecting variable

Renaming the class fixes the issue.